"""The API contract (docs/functional-requirements.md AD-4).

These pydantic models are the single source for:
- the engine's HTTP API (FastAPI response models, and so its OpenAPI);
- the TypeScript types the screens use (`npm run gen:api` -> src/api/schema.gen.ts);
- the document-processing sidecar's result schema
  (contracts/ingest-result.schema.json, contract version 2).

Change a model here, regenerate, and both sides see the change.
"""

from .admin import AuditEntry, AuditPage, ConfigVersion, DirectoryUser
from .appraisal import (
    ChecklistItemState,
    CheckArea,
    Finding,
    FindingDetail,
    FindingDetailRow,
    FindingSide,
    QueryItem,
    Readiness,
    ReviewDecisionRequest,
    ReviewItem,
)
from .case import (
    CaseCreate,
    CaseDeleteRequest,
    CaseDetail,
    CaseProgress,
    CaseSummary,
    HeaderField,
    StageKey,
    StageProgress,
    StageStatus,
)
from .common import Evidence, Grade, Stage
from .outputs import (
    Cam,
    CamSection,
    CamSummaryItem,
    CamTable,
    CamText,
    PdNote,
    PdQuestion,
    Spread,
    SpreadCell,
    SpreadColumn,
    SpreadRow,
    Working,
    WorkingCapitalAssessment,
)
from .policy import NormInput, NormOutcome, NormResult, PolicyAssessment
from .facts import (
    AccountCredits,
    AccountFact,
    AuthorityFact,
    BalanceFact,
    CaseFacts,
    Exclusion,
    FacilityFact,
    FactValue,
    FinancialYear,
    IdentityFacts,
    IncorporationFact,
    MonthFigure,
    Obligation,
    PersonEntry,
    PersonSet,
    TaxYear,
    TurnoverFigure,
    TurnoverYear,
)
from .documents import (
    Candidate,
    Classification,
    FieldValue,
    FileRecord,
    LogicalDocument,
    PageInfo,
)
from .ingest import (
    DocumentDefect,
    IngestCheck,
    IngestClassification,
    IngestConfidence,
    IngestDocument,
    IngestField,
    IngestFile,
    IngestFileResult,
    IngestPage,
    IngestRequest,
    IngestResult,
    IngestTable,
)
from .intake import (
    CaseProposal,
    Party,
    ProposalRequest,
    ProposedCandidate,
    ProposedField,
    Span,
    StrippedSpan,
    UploadResult,
)
from .session import LoginRequest, LoginResponse, Meta, Option, SessionUser

__all__ = [
    "Cam",
    "CamSection",
    "CamSummaryItem",
    "CamTable",
    "CamText",
    "PdNote",
    "PdQuestion",
    "Spread",
    "SpreadCell",
    "SpreadColumn",
    "SpreadRow",
    "Working",
    "WorkingCapitalAssessment",
    "NormInput",
    "NormOutcome",
    "NormResult",
    "PolicyAssessment",
    "AccountCredits",
    "AccountFact",
    "AuthorityFact",
    "BalanceFact",
    "CaseFacts",
    "CheckArea",
    "Exclusion",
    "FacilityFact",
    "FactValue",
    "FindingDetail",
    "FindingDetailRow",
    "FinancialYear",
    "IdentityFacts",
    "IncorporationFact",
    "MonthFigure",
    "Obligation",
    "PersonEntry",
    "PersonSet",
    "TaxYear",
    "TurnoverFigure",
    "TurnoverYear",
    "Candidate",
    "CaseProposal",
    "CaseCreate",
    "CaseDeleteRequest",
    "DocumentDefect",
    "IngestFile",
    "Party",
    "ProposalRequest",
    "ProposedCandidate",
    "ProposedField",
    "Span",
    "StrippedSpan",
    "UploadResult",
    "CaseDetail",
    "CaseSummary",
    "ChecklistItemState",
    "Classification",
    "Evidence",
    "FieldValue",
    "FileRecord",
    "Finding",
    "FindingSide",
    "Grade",
    "HeaderField",
    "IngestCheck",
    "IngestClassification",
    "IngestConfidence",
    "IngestDocument",
    "IngestField",
    "IngestPage",
    "IngestTable",
    "IngestFileResult",
    "IngestRequest",
    "IngestResult",
    "LoginRequest",
    "LoginResponse",
    "LogicalDocument",
    "Meta",
    "Option",
    "PageInfo",
    "QueryItem",
    "Readiness",
    "CaseProgress",
    "StageKey",
    "StageProgress",
    "StageStatus",
    "ReviewDecisionRequest",
    "ReviewItem",
    "SessionUser",
    "Stage",
]
