/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["login_api_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations["logout_api_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Session */
    get: operations["session_api_auth_session_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cases": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Cases */
    get: operations["list_cases_api_cases_get"];
    put?: never;
    /** Create Case */
    post: operations["create_case_api_cases_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cases/proposals": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Propose Case
     * @description F-04: parse a pasted message into a proposed case. Stores nothing.
     */
    post: operations["propose_case_api_cases_proposals_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cases/{case_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Case */
    get: operations["get_case_api_cases__case_id__get"];
    put?: never;
    post?: never;
    /**
     * Delete Case
     * @description F-01.5: delete a case and everything it owns, so testing can start
     *     again. An RM may delete only their own cases. The decision log keeps a
     *     record of the deletion; the case ID is not reused.
     */
    delete: operations["delete_case_api_cases__case_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cases/{case_id}/cam": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Case Cam
     * @description F-23: the draft CAM, every figure cited, ending in the structured summary.
     */
    get: operations["case_cam_api_cases__case_id__cam_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cases/{case_id}/checklist": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Case Checklist */
    get: operations["case_checklist_api_cases__case_id__checklist_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cases/{case_id}/documents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Case Documents */
    get: operations["case_documents_api_cases__case_id__documents_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cases/{case_id}/documents/{document_id}/pages/{page}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Document Page
     * @description F-05.6, F-16: the rendered page image (PNG) of a document's source
     *     file; `page` is the absolute page in the file, as in Evidence.
     */
    get: operations["document_page_api_cases__case_id__documents__document_id__pages__page__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cases/{case_id}/facts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Case Facts
     * @description F-18: the aligned facts the cross-checks compare, each with its evidence.
     */
    get: operations["case_facts_api_cases__case_id__facts_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cases/{case_id}/fields": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Case Fields */
    get: operations["case_fields_api_cases__case_id__fields_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cases/{case_id}/files": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Case Files */
    get: operations["case_files_api_cases__case_id__files_get"];
    put?: never;
    /**
     * Upload Files
     * @description F-05: multipart upload, field name "files" (repeatable): single files,
     *     several files or ZIP archives. Registers every file and queues processing.
     *     The body is parsed as it streams, so size limits apply before a file is
     *     held in full.
     */
    post: operations["upload_files_api_cases__case_id__files_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cases/{case_id}/findings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Case Findings */
    get: operations["case_findings_api_cases__case_id__findings_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cases/{case_id}/parties": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Case Parties
     * @description F-10.2: the case's party set with sources and attributed KYC.
     */
    get: operations["case_parties_api_cases__case_id__parties_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cases/{case_id}/pd-note": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Case Pd Note
     * @description F-24: questions for the personal discussion, ranked, each tied to its source.
     */
    get: operations["case_pd_note_api_cases__case_id__pd_note_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cases/{case_id}/policy": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Case Policy
     * @description F-20: every norm with its required and actual value, source figures and outcome.
     */
    get: operations["case_policy_api_cases__case_id__policy_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cases/{case_id}/progress": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Case Progress
     * @description FRD §6: each processing stage's status and counts, for the stage
     *     progress in the case workspace. Counts only, so every role may read it.
     */
    get: operations["case_progress_api_cases__case_id__progress_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cases/{case_id}/queries": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Case Queries */
    get: operations["case_queries_api_cases__case_id__queries_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cases/{case_id}/spread": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Case Spread
     * @description F-22: the spread (interim layout) with ratios and the working-capital assessment.
     */
    get: operations["case_spread_api_cases__case_id__spread_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/config/checklist-taxonomy": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Config Checklist Taxonomy */
    get: operations["config_checklist_taxonomy_api_config_checklist_taxonomy_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/config/document-types": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Config Document Types */
    get: operations["config_document_types_api_config_document_types_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/config/policy": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Config Policy */
    get: operations["config_policy_api_config_policy_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/config/version": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Config Version */
    get: operations["config_version_api_config_version_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/meta": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Meta */
    get: operations["meta_api_meta_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/review": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Review Queue */
    get: operations["review_queue_api_review_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/review/{item_id}/decision": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Decide Review
     * @description F-17.5: confirm, correct, waive or assign, with a reason. Recorded as
     *     an overlay; never changes configuration.
     */
    post: operations["decide_review_api_review__item_id__decision_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AccountCredits
     * @description One account's credits, before and after cleansing (F-18.2).
     */
    AccountCredits: {
      /** Account */
      account: string;
      /** Excluded */
      excluded: number;
      /** Exclusions */
      exclusions: components["schemas"]["Exclusion"][];
      /** Gross */
      gross: number;
      /** Months */
      months: string[];
      /** Net */
      net: number;
    };
    /**
     * AccountFact
     * @description One bank account and where it is evidenced (F-18.5).
     */
    AccountFact: {
      /** Bank */
      bank: string;
      /** Declared */
      declared: boolean;
      /** Evidence */
      evidence?: components["schemas"]["Evidence"][];
      /** Has Statement */
      has_statement: boolean;
      /** Label */
      label: string;
      /** Last4 */
      last4: string | null;
      /** Sources */
      sources: string[];
    };
    /**
     * Cam
     * @description The draft Credit Approval Memo (F-23).
     */
    Cam: {
      /** Case Id */
      case_id: string;
      /** Interim Template */
      interim_template: boolean;
      /**
       * Recommendation
       * @default
       */
      recommendation: string;
      /** Recommendation Title */
      recommendation_title: string;
      /** Sections */
      sections: components["schemas"]["CamSection"][];
      /** Summary */
      summary: components["schemas"]["CamSummaryItem"][];
      /** Summary Title */
      summary_title: string;
    };
    /** CamSection */
    CamSection: {
      /** Empty */
      empty?: string | null;
      /** Id */
      id: string;
      /** Paragraphs */
      paragraphs?: components["schemas"]["CamText"][];
      table?: components["schemas"]["CamTable"] | null;
      /** Title */
      title: string;
    };
    /** CamSummaryItem */
    CamSummaryItem: {
      /** Citations */
      citations?: components["schemas"]["Evidence"][];
      /**
       * Kind
       * @enum {string}
       */
      kind: "finding" | "deviation" | "query";
      /** Ref */
      ref: string;
      /** Severity */
      severity?: ("serious" | "moderate" | "mild") | null;
      /** Text */
      text: string;
    };
    /** CamTable */
    CamTable: {
      /** Columns */
      columns: string[];
      /** Rows */
      rows: components["schemas"]["CamText"][][];
    };
    /**
     * CamText
     * @description A statement in the memo with the pages it rests on (F-23.2).
     */
    CamText: {
      /** Citations */
      citations?: components["schemas"]["Evidence"][];
      /** Text */
      text: string;
    };
    /** Candidate */
    Candidate: {
      /** Confidence */
      confidence: number;
      /** Type Id */
      type_id: string;
    };
    /**
     * CaseCreate
     * @description Create a case after the RM confirms (F-04.7). The proposal flow
     *     (F-04) fills `header` with sources; a direct create leaves it empty.
     */
    CaseCreate: {
      /** Amount Inr */
      amount_inr: number;
      /** Borrower */
      borrower: string;
      /** Channel */
      channel: string;
      /** Cin */
      cin?: string | null;
      /**
       * Collateral Present
       * @default false
       */
      collateral_present: boolean;
      /**
       * Constitution
       * @default unknown
       */
      constitution: string;
      /** Duplicate Override Reason */
      duplicate_override_reason?: string | null;
      /** Facilities */
      facilities: string[];
      /** Gstin */
      gstin?: string | null;
      /** Header */
      header?: {
        [key: string]: components["schemas"]["HeaderField"];
      };
      /** Message Text */
      message_text?: string | null;
      /** Pan */
      pan?: string | null;
      /** Udyam */
      udyam?: string | null;
    };
    /**
     * CaseDeleteRequest
     * @description F-01.5: why the case is being deleted; kept in the decision log.
     */
    CaseDeleteRequest: {
      /** Reason */
      reason: string;
    };
    /** CaseDetail */
    CaseDetail: {
      /** Amount Inr */
      amount_inr: number;
      /** As Of */
      as_of: string;
      /** Borrower */
      borrower: string;
      /** Channel */
      channel: string;
      /** Cin */
      cin: string | null;
      /** Collateral Present */
      collateral_present: boolean;
      /** Config Version */
      config_version: string | null;
      /** Constitution */
      constitution: string;
      /** Created At */
      created_at: string;
      /** Created By */
      created_by: string;
      /** Facilities */
      facilities: string[];
      /** Gstin */
      gstin: string | null;
      /** Header */
      header: {
        [key: string]: components["schemas"]["HeaderField"];
      };
      /** Id */
      id: string;
      /** Open Review Items */
      open_review_items: number;
      /** Pan */
      pan: string | null;
      /** Rm */
      rm: string;
      /**
       * Stage
       * @enum {string}
       */
      stage:
        | "Intake"
        | "Documents"
        | "Extraction"
        | "Completeness"
        | "CrossVerification"
        | "Policy"
        | "Outputs"
        | "Completed";
      /** Udyam */
      udyam: string | null;
    };
    /** CaseFacts */
    CaseFacts: {
      /** Accounts */
      accounts: components["schemas"]["AccountFact"][];
      /** Case Id */
      case_id: string;
      /** Credits */
      credits: components["schemas"]["AccountCredits"][];
      /** Declaration Received */
      declaration_received: boolean;
      /** Facilities */
      facilities: components["schemas"]["FacilityFact"][];
      identities: components["schemas"]["IdentityFacts"];
      /** Obligations */
      obligations: components["schemas"]["Obligation"][];
      /** Persons */
      persons: components["schemas"]["PersonSet"][];
      /** Turnover */
      turnover: components["schemas"]["TurnoverYear"][];
    };
    /** CaseProgress */
    CaseProgress: {
      /** Case Id */
      case_id: string;
      /**
       * Stage
       * @enum {string}
       */
      stage:
        | "Intake"
        | "Documents"
        | "Extraction"
        | "Completeness"
        | "CrossVerification"
        | "Policy"
        | "Outputs"
        | "Completed";
      /** Stages */
      stages: components["schemas"]["StageProgress"][];
    };
    /**
     * CaseProposal
     * @description What the pasted message proposes (F-04). Nothing is stored until the
     *     RM confirms and posts a CaseCreate (F-04.7).
     */
    CaseProposal: {
      /** Duplicates */
      duplicates?: components["schemas"]["CaseSummary"][];
      /** Fields */
      fields: {
        [key: string]: components["schemas"]["ProposedField"];
      };
      /** Missing Minimum */
      missing_minimum?: string[];
      /** Stripped */
      stripped?: components["schemas"]["StrippedSpan"][];
      /** Text Sha256 */
      text_sha256: string;
    };
    /**
     * CaseSummary
     * @description Workbench row (F-01.4).
     */
    CaseSummary: {
      /** Amount Inr */
      amount_inr: number;
      /** Borrower */
      borrower: string;
      /** Constitution */
      constitution: string;
      /** Created At */
      created_at: string;
      /** Facilities */
      facilities: string[];
      /** Id */
      id: string;
      /** Open Review Items */
      open_review_items: number;
      /** Rm */
      rm: string;
      /**
       * Stage
       * @enum {string}
       */
      stage:
        | "Intake"
        | "Documents"
        | "Extraction"
        | "Completeness"
        | "CrossVerification"
        | "Policy"
        | "Outputs"
        | "Completed";
    };
    /** ChecklistItemDef */
    ChecklistItemDef: {
      /** Basis */
      basis: string;
      /** Blocking */
      blocking: boolean;
      /** Category */
      category: string;
      /** Constitutions */
      constitutions: ("private_limited" | "proprietorship" | "partnership")[];
      coverage?: components["schemas"]["CoverageRule"] | null;
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Request */
      request?: string | null;
      /** Requires Attributes */
      requires_attributes?: string[];
      /**
       * Source
       * @enum {string}
       */
      source: "published_policy" | "regulatory" | "industry_standard" | "provisional";
      /** Weight */
      weight: number;
      /** Why */
      why: string;
    };
    /** ChecklistItemState */
    ChecklistItemState: {
      /** Basis */
      basis: string;
      /** Blocking */
      blocking: boolean;
      /** Deficiency */
      deficiency?: string | null;
      /** Document Ids */
      document_ids?: string[];
      /** Item Id */
      item_id: string;
      /** Name */
      name: string;
      /** Section */
      section: string;
      /**
       * Status
       * @enum {string}
       */
      status: "satisfied" | "insufficient" | "missing" | "in_review" | "waived";
      /** Weight */
      weight: number;
      /** Why */
      why: string;
    };
    /**
     * ChecklistTaxonomySection
     * @description config/checklist_taxonomy.yaml
     */
    ChecklistTaxonomySection: {
      /** Disbursement Gate Threshold */
      disbursement_gate_threshold: number;
      /** Items */
      items: components["schemas"]["ChecklistItemDef"][];
      /** Review Gate Threshold */
      review_gate_threshold: number;
      /** Section Weight */
      section_weight: {
        [key: string]: number;
      };
      /** Sections */
      sections: string[];
    };
    /**
     * Classification
     * @description F-09.4: what was found, how it exited, and the runners-up.
     */
    Classification: {
      /** Candidates */
      candidates?: components["schemas"]["Candidate"][];
      /** Confidence */
      confidence: number;
      /**
       * Exit Tier
       * @enum {string}
       */
      exit_tier: "signals" | "layout" | "model" | "person" | "none";
      /** Signals */
      signals?: string[];
      /** Types */
      types: string[];
    };
    /**
     * CoverageRule
     * @description What "complete" means for an item beyond presence (F-13.2), always
     *     measured from the case's fixed as_of date (principle 8).
     */
    CoverageRule: {
      /**
       * Count
       * @default 0
       */
      count: number;
      /**
       * Kind
       * @enum {string}
       */
      kind:
        | "financial_year"
        | "assessment_years"
        | "monthly_periods"
        | "account_months"
        | "parties"
        | "statements";
      /**
       * Months
       * @default 0
       */
      months: number;
      /**
       * Offset
       * @default 0
       */
      offset: number;
      /** Statements */
      statements?: string[];
    };
    /** DeviationCategory */
    DeviationCategory: {
      /** Key */
      key: string;
      /** Label */
      label: string;
    };
    /** DocumentTypeDef */
    DocumentTypeDef: {
      /** Description */
      description: string;
      /**
       * Group
       * @enum {string}
       */
      group:
        | "origination"
        | "constitution"
        | "registration"
        | "kyc"
        | "financials"
        | "tax"
        | "banking"
        | "working_capital"
        | "collateral"
        | "bureau"
        | "other_known";
      /** Id */
      id: string;
      /**
       * Instance Key
       * @default none
       * @enum {string}
       */
      instance_key: "none" | "period" | "year" | "account" | "person" | "property";
      /** Name */
      name: string;
      /**
       * Partner Output
       * @default false
       */
      partner_output: boolean;
      party_list?: components["schemas"]["PartyList"] | null;
      /**
       * Personal
       * @default false
       */
      personal: boolean;
      /** Satisfies */
      satisfies?: string[];
    };
    /**
     * DocumentTypesSection
     * @description config/document_types.yaml (F-00.4).
     */
    DocumentTypesSection: {
      /** Types */
      types: components["schemas"]["DocumentTypeDef"][];
    };
    /**
     * Evidence
     * @description Where a value came from (FRD §7, F-16). Page is mandatory (C7); the
     *     region is optional, as normalised page coordinates (0 to 1, top-left
     *     origin): [x0, y0, x1, y1].
     */
    Evidence: {
      /** Bbox */
      bbox?: [number, number, number, number] | null;
      /** Document Id */
      document_id: string;
      /** Page */
      page: number;
    };
    /**
     * Exclusion
     * @description A credit removed before counting business inflow (F-18.2).
     */
    Exclusion: {
      /** Account */
      account: string;
      /** Amount */
      amount: number;
      /** Date */
      date: string | null;
      /** Evidence */
      evidence?: components["schemas"]["Evidence"][];
      /** Label */
      label: string;
      /** Narration */
      narration: string;
      /** Rule */
      rule: string;
    };
    /**
     * FacilityFact
     * @description An existing facility as one source records it (F-19 OB-01).
     */
    FacilityFact: {
      /** Amount */
      amount?: number | null;
      /** Emi */
      emi?: number | null;
      /** Evidence */
      evidence?: components["schemas"]["Evidence"][];
      /** Facility */
      facility?: string | null;
      /** Label */
      label: string;
      /** Lender */
      lender: string;
      /**
       * Relies On Manual
       * @default false
       */
      relies_on_manual: boolean;
      /** Source */
      source: string;
    };
    /**
     * FactValue
     * @description One source's value for a fact, with where it came from (F-18.6).
     */
    FactValue: {
      /** Evidence */
      evidence?: components["schemas"]["Evidence"][];
      /** Field Ids */
      field_ids?: string[];
      /** Label */
      label: string;
      /**
       * Relies On Manual
       * @default false
       */
      relies_on_manual: boolean;
      /** Source */
      source: string;
      /** Value */
      value: string | number | null;
    };
    /**
     * FieldValue
     * @description One extracted value with its evidence and confidence (F-15, F-17).
     */
    FieldValue: {
      /** Case Id */
      case_id: string;
      /** Confidence */
      confidence?: number | null;
      /** Confidence Components */
      confidence_components?: {
        [key: string]: number;
      };
      /** Corrected Value */
      corrected_value?: string | number | boolean | null;
      /** Document Id */
      document_id: string;
      evidence?: components["schemas"]["Evidence"] | null;
      /** Field */
      field: string;
      /** Id */
      id: string;
      /**
       * Method
       * @enum {string}
       */
      method: "deterministic" | "model" | "manual" | "person";
      /** Missing Reason */
      missing_reason?: string | null;
      /** Raw */
      raw?: string | null;
      /**
       * Status
       * @enum {string}
       */
      status: "accepted" | "in_review" | "corrected" | "missing" | "rejected";
      /** Value */
      value: string | number | boolean | null;
    };
    /**
     * FileRecord
     * @description Bytes as received (F-05). Every file ends in a visible state (F-05.5).
     */
    FileRecord: {
      /** Archive Path */
      archive_path?: string | null;
      /** Case Id */
      case_id: string;
      /** Channel */
      channel: string;
      /** Content Type */
      content_type: string;
      /** Duplicate Of */
      duplicate_of?: string | null;
      /** Id */
      id: string;
      /** Label Hint */
      label_hint?: string | null;
      /** Original Name */
      original_name: string;
      /** Reason */
      reason?: string | null;
      /** Sha256 */
      sha256: string;
      /** Size Bytes */
      size_bytes: number;
      /**
       * Status
       * @enum {string}
       */
      status: "registered" | "duplicate" | "ignored" | "rejected" | "exception";
      /** Uploaded At */
      uploaded_at: string;
      /** Uploaded By */
      uploaded_by: string;
    };
    /**
     * Finding
     * @description A cross-check or policy outcome (F-19, F-20).
     */
    Finding: {
      /** Blocking */
      blocking: boolean;
      /** Case Id */
      case_id: string;
      /** Config Version */
      config_version?: string | null;
      /** Explanation */
      explanation: string;
      /** Id */
      id: string;
      /**
       * Outcome
       * @enum {string}
       */
      outcome: "pass" | "fail" | "incomplete" | "not_applicable";
      /** Query */
      query?: string | null;
      /** Rule Id */
      rule_id: string;
      /** Run Id */
      run_id?: string | null;
      /**
       * Severity
       * @enum {string}
       */
      severity: "serious" | "moderate" | "mild";
      /** Sides */
      sides: components["schemas"]["FindingSide"][];
      /** Title */
      title: string;
      /** Tolerance */
      tolerance?: string | null;
    };
    /** FindingSide */
    FindingSide: {
      /** Evidence */
      evidence?: components["schemas"]["Evidence"][];
      /** Label */
      label: string;
      /**
       * Relies On Manual
       * @default false
       */
      relies_on_manual: boolean;
      /** Value */
      value: string | number | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * HeaderField
     * @description One case-header field with both values kept (F-01.2): what the system
     *     proposed and where from, and what a person confirmed.
     */
    HeaderField: {
      /** Proposed */
      proposed?: string | null;
      /** Source */
      source?: string | null;
      /** Value */
      value: string | null;
    };
    /** IdentityFacts */
    IdentityFacts: {
      /** Entity Pan */
      entity_pan?: components["schemas"]["FactValue"][];
      /** Gstin */
      gstin?: components["schemas"]["FactValue"][];
      /** Legal Name */
      legal_name?: components["schemas"]["FactValue"][];
    };
    /**
     * LogicalDocument
     * @description One logical document: a file and a page range (F-08).
     */
    LogicalDocument: {
      /** Case Id */
      case_id: string;
      classification: components["schemas"]["Classification"] | null;
      /** Config Version */
      config_version?: string | null;
      /** Duplicate Of */
      duplicate_of?: string | null;
      /** File Id */
      file_id: string;
      /**
       * Grade
       * @enum {string}
       */
      grade: "A" | "B" | "C" | "U";
      /** Id */
      id: string;
      /** Instance Key */
      instance_key?: string | null;
      /**
       * Label Mismatch
       * @default false
       */
      label_mismatch: boolean;
      /** Page From */
      page_from: number;
      /** Page To */
      page_to: number;
      /** Pages */
      pages: components["schemas"]["PageInfo"][];
      /** Party Id */
      party_id?: string | null;
      /**
       * Status
       * @enum {string}
       */
      status:
        | "received"
        | "graded"
        | "split"
        | "classified"
        | "unclassified"
        | "extracted"
        | "accepted"
        | "in_review"
        | "in_exception"
        | "superseded"
        | "duplicate";
      /** Version Of */
      version_of?: string | null;
    };
    /** LoginRequest */
    LoginRequest: {
      /** Email */
      email: string;
      /** Password */
      password: string;
    };
    /** LoginResponse */
    LoginResponse: {
      /** Token */
      token: string;
      user: components["schemas"]["SessionUser"];
    };
    /**
     * Meta
     * @description Choice lists the screens need, from config/app.yaml.
     */
    Meta: {
      /** Case Create Minimum */
      case_create_minimum: string[];
      /** Channels */
      channels: components["schemas"]["Option"][];
      /** Constitutions */
      constitutions: components["schemas"]["Option"][];
      /** Facilities */
      facilities: components["schemas"]["Option"][];
    };
    /**
     * NormInput
     * @description One source figure a norm used, with where it came from (F-20.2).
     */
    NormInput: {
      /** Evidence */
      evidence?: components["schemas"]["Evidence"][];
      /** Label */
      label: string;
      /** Name */
      name: string;
      /**
       * Relies On Manual
       * @default false
       */
      relies_on_manual: boolean;
      /** Value */
      value: number | null;
    };
    /** NormResult */
    NormResult: {
      /** Actual */
      actual?: number | null;
      /** Category */
      category: string;
      /** Category Label */
      category_label: string;
      /**
       * Family
       * @enum {string}
       */
      family: "eligibility" | "ratios" | "security_cover" | "documentation";
      /** Formula */
      formula: string;
      /** Id */
      id: string;
      /** Inputs */
      inputs?: components["schemas"]["NormInput"][];
      /** Label */
      label: string;
      /** Missing */
      missing?: string[];
      /** Note */
      note?: string | null;
      /**
       * Outcome
       * @enum {string}
       */
      outcome: "pass" | "deviation" | "cannot_evaluate" | "not_applicable";
      /**
       * Provisional
       * @default false
       */
      provisional: boolean;
      /** Required */
      required: string;
      /** Unit */
      unit?: string | null;
    };
    /**
     * Obligation
     * @description A recurring debit that looks like a loan instalment (F-18.4).
     */
    Obligation: {
      /** Account */
      account: string;
      /** Debits */
      debits: number;
      /** Evidence */
      evidence?: components["schemas"]["Evidence"][];
      /** Lender */
      lender: string;
      /** Months */
      months: string[];
      /** Typical Amount */
      typical_amount: number;
      /** Variants */
      variants: string[];
    };
    /** Option */
    Option: {
      /** Id */
      id: string;
      /** Label */
      label: string;
    };
    /** PageInfo */
    PageInfo: {
      /**
       * Grade
       * @enum {string}
       */
      grade: "A" | "B" | "C" | "U";
      /** N */
      n: number;
      /** Ocr Confidence */
      ocr_confidence?: number | null;
      /** Reasons */
      reasons?: string[];
      /**
       * Route
       * @enum {string}
       */
      route: "text" | "ocr" | "sheet";
    };
    /**
     * Party
     * @description A person or entity on the case: director, partner, proprietor,
     *     guarantor or the borrower itself (F-10.2).
     */
    Party: {
      /** Case Id */
      case_id: string;
      /** Din */
      din?: string | null;
      /** Id */
      id: string;
      /** Kyc Document Ids */
      kyc_document_ids?: string[];
      /** Name */
      name: string;
      /** Pan */
      pan?: string | null;
      /**
       * Role
       * @enum {string}
       */
      role: "borrower" | "director" | "partner" | "proprietor" | "guarantor" | "promoter";
      /** Source */
      source: string;
    };
    /**
     * PartyList
     * @description A list of people a document names (F-10.2): the field that holds them and, for a list of
     *     objects, the key of each part. A plain list of names has no `name_key`.
     */
    PartyList: {
      /** Designation Key */
      designation_key?: string | null;
      /** Din Key */
      din_key?: string | null;
      /** Field */
      field: string;
      /** Name Key */
      name_key?: string | null;
      /** Pan Key */
      pan_key?: string | null;
      /** Role */
      role?: string | null;
    };
    /** PdNote */
    PdNote: {
      /** Case Id */
      case_id: string;
      /** Questions */
      questions: components["schemas"]["PdQuestion"][];
    };
    /**
     * PdQuestion
     * @description One question for the personal discussion (F-24).
     */
    PdQuestion: {
      /** Evidence */
      evidence?: components["schemas"]["Evidence"][];
      /** Id */
      id: string;
      /** Ref */
      ref: string;
      /** Rule */
      rule: string;
      /**
       * Severity
       * @enum {string}
       */
      severity: "serious" | "moderate" | "mild";
      /**
       * Source
       * @enum {string}
       */
      source: "finding" | "deviation" | "gap";
      /** Text */
      text: string;
      /** Title */
      title: string;
    };
    /**
     * PersonSet
     * @description The promoters one source names (F-18.3: variants resolved later).
     */
    PersonSet: {
      /** Evidence */
      evidence?: components["schemas"]["Evidence"][];
      /** Label */
      label: string;
      /** Names */
      names: string[];
      /**
       * Relies On Manual
       * @default false
       */
      relies_on_manual: boolean;
      /** Source */
      source: string;
    };
    /** PolicyAssessment */
    PolicyAssessment: {
      /** Case Id */
      case_id: string;
      /** Norms */
      norms: components["schemas"]["NormResult"][];
      /** Period */
      period: string | null;
    };
    /**
     * PolicyNorm
     * @description One norm (F-20.1): an expression over POLICY_INPUTS, a threshold, the
     *     deviation category a breach falls under, and its source. A ratio norm
     *     takes its label, unit, direction and threshold from `ratios`.
     */
    PolicyNorm: {
      /**
       * Applies When
       * @default always
       * @enum {string}
       */
      applies_when: "always" | "working_capital" | "term_debt" | "collateral";
      /** Category */
      category: string;
      /** Expression */
      expression: string;
      /**
       * Family
       * @enum {string}
       */
      family: "eligibility" | "ratios" | "security_cover" | "documentation";
      /** Id */
      id: string;
      /** Kind */
      kind?: ("min" | "max") | null;
      /** Label */
      label?: string | null;
      /** Note */
      note?: string | null;
      /** Pd Question */
      pd_question?: string | null;
      /** Ratio */
      ratio?: string | null;
      /** Source */
      source?: ("published_policy" | "regulatory" | "industry_standard" | "provisional") | null;
      /** Status */
      status?: ("active" | "provisional") | null;
      /** Threshold */
      threshold?: number | null;
      /** Unit */
      unit?: ("x" | "%" | "days" | "years" | "inr" | "count" | "rank") | null;
    };
    /** PolicyRatio */
    PolicyRatio: {
      /** Acceptable */
      acceptable: number;
      /** Applies */
      applies: string;
      /** Formula */
      formula: string;
      /** Hard Floor */
      hard_floor?: string | null;
      /** Key */
      key: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: "min" | "max";
      /** Label */
      label: string;
      /** Marginal */
      marginal: number;
      /** Note */
      note: string;
      /**
       * Source
       * @enum {string}
       */
      source: "published_policy" | "regulatory" | "industry_standard" | "provisional";
      /**
       * Status
       * @enum {string}
       */
      status: "active" | "provisional";
      /**
       * Unit
       * @enum {string}
       */
      unit: "x" | "%" | "days";
    };
    /**
     * PolicySection
     * @description config/policy.yaml
     */
    PolicySection: {
      /** Available Ratios */
      available_ratios?: components["schemas"]["PolicyRatio"][];
      /** Deviation Categories */
      deviation_categories?: components["schemas"]["DeviationCategory"][];
      /** Norms */
      norms?: components["schemas"]["PolicyNorm"][];
      /** Pd Questions */
      pd_questions?: {
        [key: string]: string;
      };
      /** Ratios */
      ratios: components["schemas"]["PolicyRatio"][];
      working_capital: components["schemas"]["WorkingCapitalPolicy"];
    };
    /** ProposalRequest */
    ProposalRequest: {
      /** Channel */
      channel: string;
      /** Text */
      text: string;
    };
    /** ProposedCandidate */
    ProposedCandidate: {
      span: components["schemas"]["Span"];
      /** Value */
      value: string;
    };
    /**
     * ProposedField
     * @description F-04.3: a value is proposed only with its span in the message.
     */
    ProposedField: {
      /** Candidates */
      candidates?: components["schemas"]["ProposedCandidate"][];
      /** Note */
      note?: string | null;
      span?: components["schemas"]["Span"] | null;
      /**
       * Status
       * @enum {string}
       */
      status: "found" | "unclear" | "not_found" | "invalid";
      /** Value */
      value: string | null;
    };
    /**
     * QueryItem
     * @description One line of the pre-login query list (F-14).
     */
    QueryItem: {
      /** Case Id */
      case_id: string;
      /** Evidence */
      evidence?: components["schemas"]["Evidence"][];
      /**
       * Group
       * @enum {string}
       */
      group: "documents_needed" | "documents_to_redo" | "clarifications";
      /** Id */
      id: string;
      /**
       * Resolved
       * @default false
       */
      resolved: boolean;
      /**
       * Source Kind
       * @enum {string}
       */
      source_kind: "checklist" | "quality" | "label" | "party" | "finding";
      /** Source Ref */
      source_ref: string;
      /** Text */
      text: string;
    };
    /**
     * Readiness
     * @description F-13.4: weighted proportion satisfied, against the configured gate.
     */
    Readiness: {
      /** Blocking Open */
      blocking_open: number;
      /** Gate Met */
      gate_met: boolean;
      /** Gate Pct */
      gate_pct: number;
      /** Items */
      items: components["schemas"]["ChecklistItemState"][];
      /** Provisional */
      provisional: boolean;
      /**
       * Ready For Credit
       * @default false
       */
      ready_for_credit: boolean;
      /** Score Pct */
      score_pct: number;
    };
    /** ReviewDecisionRequest */
    ReviewDecisionRequest: {
      /**
       * Decision
       * @enum {string}
       */
      decision: "confirm" | "correct" | "waive" | "assign";
      /** Reason */
      reason?: string | null;
      /** Value */
      value?: string | number | boolean | null;
      /** Values */
      values?: {
        [key: string]: string | number | boolean | null;
      } | null;
    };
    /**
     * ReviewItem
     * @description Something waiting for a person (F-17.4).
     */
    ReviewItem: {
      /** Case Id */
      case_id: string;
      /** Created At */
      created_at: string;
      /** Decided At */
      decided_at?: string | null;
      /** Decided By */
      decided_by?: string | null;
      /** Decision */
      decision?: ("confirm" | "correct" | "waive" | "assign") | null;
      /** Id */
      id: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: "type" | "field" | "quality" | "party" | "split" | "manual_entry" | "finding";
      /** Maker */
      maker?: string | null;
      /** Reason */
      reason?: string | null;
      /** Ref */
      ref: string;
      /**
       * Status
       * @enum {string}
       */
      status: "open" | "decided";
      /** Summary */
      summary: string;
    };
    /** SessionUser */
    SessionUser: {
      /** Branch */
      branch: string;
      /** Email */
      email: string;
      /** Id */
      id: string;
      /** Initials */
      initials: string;
      /** Name */
      name: string;
      /** Navgroups */
      navGroups: string[];
      /** Permissions */
      permissions: string[];
      /** Role */
      role: string;
      /** Rolelabel */
      roleLabel: string;
    };
    /**
     * Span
     * @description Character offsets into the pasted message: [start, end).
     */
    Span: {
      /** End */
      end: number;
      /** Start */
      start: number;
    };
    /** Spread */
    Spread: {
      /** Case Id */
      case_id: string;
      /** Columns */
      columns: components["schemas"]["SpreadColumn"][];
      /**
       * Interim
       * @default true
       */
      interim: boolean;
      /** Rows */
      rows: components["schemas"]["SpreadRow"][];
      working_capital: components["schemas"]["WorkingCapitalAssessment"];
    };
    /** SpreadCell */
    SpreadCell: {
      /** Evidence */
      evidence?: components["schemas"]["Evidence"][];
      /**
       * Relies On Manual
       * @default false
       */
      relies_on_manual: boolean;
      /** Value */
      value?: number | null;
    };
    /**
     * SpreadColumn
     * @description One year of one kind of statement.
     */
    SpreadColumn: {
      /**
       * Basis
       * @enum {string}
       */
      basis: "audited" | "provisional" | "projected";
      /** Fy */
      fy: string;
      /** Key */
      key: string;
      /** Period End */
      period_end: string;
    };
    /** SpreadRow */
    SpreadRow: {
      /** Cells */
      cells: components["schemas"]["SpreadCell"][];
      /** Formula */
      formula?: string | null;
      /** Key */
      key: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: "line" | "derived" | "ratio";
      /** Label */
      label: string;
      /**
       * Section
       * @enum {string}
       */
      section: "profit_and_loss" | "balance_sheet" | "ratios";
      /**
       * Unit
       * @enum {string}
       */
      unit: "inr" | "x" | "%" | "days";
    };
    /**
     * StageProgress
     * @description One processing stage of FRD §5, as the case workspace shows it (§6).
     *     Counts only, never extracted values, so every role may read it.
     */
    StageProgress: {
      /**
       * Attention
       * @default 0
       */
      attention: number;
      /**
       * Done
       * @default 0
       */
      done: number;
      /**
       * Key
       * @enum {string}
       */
      key:
        "documents" | "extraction" | "completeness" | "cross_verification" | "policy" | "outputs";
      /**
       * Status
       * @enum {string}
       */
      status: "not_started" | "in_progress" | "needs_attention" | "done";
      /**
       * Total
       * @default 0
       */
      total: number;
    };
    /**
     * StrippedSpan
     * @description Part of the message set aside before extraction but kept as
     *     provenance (F-04, normalisation): nothing is proposed from it.
     */
    StrippedSpan: {
      /**
       * Kind
       * @enum {string}
       */
      kind: "timestamp" | "sender" | "header" | "quoted" | "signature";
      span: components["schemas"]["Span"];
    };
    /**
     * TurnoverFigure
     * @description One source's turnover for one financial year (F-18.1).
     */
    TurnoverFigure: {
      /** Evidence */
      evidence?: components["schemas"]["Evidence"][];
      /** Field Ids */
      field_ids?: string[];
      /** Label */
      label: string;
      /** Months Covered */
      months_covered?: number | null;
      /** Months Missing */
      months_missing?: string[];
      /**
       * Relies On Manual
       * @default false
       */
      relies_on_manual: boolean;
      /**
       * Source
       * @enum {string}
       */
      source: "financials" | "gst" | "bank" | "declared";
      /** Value */
      value: number | null;
    };
    /** TurnoverYear */
    TurnoverYear: {
      /** Figures */
      figures: components["schemas"]["TurnoverFigure"][];
      /** Fy */
      fy: string;
      /** Fy End */
      fy_end: string;
    };
    /**
     * UploadResult
     * @description F-05.5: every file ends in a visible state; archives list their members.
     */
    UploadResult: {
      /** Files */
      files: components["schemas"]["FileRecord"][];
      /** Job Id */
      job_id?: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /**
     * Working
     * @description One step of the working-capital assessment (F-22.2).
     */
    Working: {
      /** Basis */
      basis?: string | null;
      /** Evidence */
      evidence?: components["schemas"]["Evidence"][];
      /** Label */
      label: string;
      /**
       * Unit
       * @default inr
       * @enum {string}
       */
      unit: "inr" | "%";
      /** Value */
      value: number | null;
    };
    /** WorkingCapitalAssessment */
    WorkingCapitalAssessment: {
      /** Column */
      column?: string | null;
      /** Eligible */
      eligible?: number | null;
      /**
       * Method
       * @enum {string}
       */
      method: "turnover" | "mpbf" | "not_applicable";
      /** Missing */
      missing?: string[];
      /** Reason */
      reason: string;
      /** Requested */
      requested: number;
      /** Steps */
      steps?: components["schemas"]["Working"][];
    };
    /** WorkingCapitalPolicy */
    WorkingCapitalPolicy: {
      /** Mpbf Above Limit Inr */
      mpbf_above_limit_inr: number;
      /**
       * Mpbf Margin Pct
       * @default 25
       */
      mpbf_margin_pct: number;
      /**
       * Source
       * @enum {string}
       */
      source: "published_policy" | "regulatory" | "industry_standard" | "provisional";
      /**
       * Status
       * @enum {string}
       */
      status: "active" | "provisional";
      /**
       * Turnover Margin Pct
       * @default 5
       */
      turnover_margin_pct: number;
      /**
       * Turnover Requirement Pct
       * @default 25
       */
      turnover_requirement_pct: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  login_api_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  logout_api_auth_logout_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  session_api_auth_session_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionUser"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_cases_api_cases_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CaseSummary"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_case_api_cases_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CaseCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CaseDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  propose_case_api_cases_proposals_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProposalRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CaseProposal"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_case_api_cases__case_id__get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        case_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CaseDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_case_api_cases__case_id__delete: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        case_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CaseDeleteRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  case_cam_api_cases__case_id__cam_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        case_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Cam"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  case_checklist_api_cases__case_id__checklist_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        case_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Readiness"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  case_documents_api_cases__case_id__documents_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        case_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LogicalDocument"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  document_page_api_cases__case_id__documents__document_id__pages__page__get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        case_id: string;
        document_id: string;
        page: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  case_facts_api_cases__case_id__facts_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        case_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CaseFacts"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  case_fields_api_cases__case_id__fields_get: {
    parameters: {
      query?: {
        document_id?: string | null;
      };
      header?: {
        authorization?: string | null;
      };
      path: {
        case_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FieldValue"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  case_files_api_cases__case_id__files_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        case_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FileRecord"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  upload_files_api_cases__case_id__files_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        case_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          channel?: string;
          files: string[];
        };
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UploadResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  case_findings_api_cases__case_id__findings_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        case_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Finding"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  case_parties_api_cases__case_id__parties_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        case_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Party"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  case_pd_note_api_cases__case_id__pd_note_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        case_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PdNote"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  case_policy_api_cases__case_id__policy_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        case_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PolicyAssessment"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  case_progress_api_cases__case_id__progress_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        case_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CaseProgress"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  case_queries_api_cases__case_id__queries_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        case_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QueryItem"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  case_spread_api_cases__case_id__spread_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        case_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Spread"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  config_checklist_taxonomy_api_config_checklist_taxonomy_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChecklistTaxonomySection"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  config_document_types_api_config_document_types_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentTypesSection"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  config_policy_api_config_policy_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PolicySection"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  config_version_api_config_version_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  meta_api_meta_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Meta"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  review_queue_api_review_get: {
    parameters: {
      query?: {
        case_id?: string | null;
        include_decided?: boolean;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReviewItem"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  decide_review_api_review__item_id__decision_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        item_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReviewDecisionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReviewItem"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
