// Library surface, for applications that embed the engine in-process instead of calling it over HTTP.
export { extract, withRules, type ExtractRequest, type ExtractResponse, type DocumentResult, type ServiceEvent } from './service.js'
export { runSections, PROMPT_VERSION, type SectionsResult, type Subject } from './pipeline.js'
export { acquire, parseBytes, fromEmail, fromUrl, type Channel, type Document, type RawInput } from './inputs.js'
export { BUILT_IN, GENERIC, inlineProfile, compileFields, strictify, outputSchema, type Profile, type Field, type InlineProfile, type SectionsSpec } from './profiles.js'
export { listPacks, loadPack, resolveType, savePack, validate, fewShot, type Pack, type PackFile, type Signatures, type Validator, type Example } from './catalogue.js'
export { classify, bySignature, type Classification } from './classify.js'
export { recordFeedback, type Feedback } from './feedback.js'
export { summary as metrics, type TypeSummary } from './metrics.js'
export { listReview, clusters, propose, type ReviewItem, type Cluster, type Proposal } from './review.js'
export { createIngestApp, apiKeyAuth, ServiceError } from './app.js'
export { toText, fetchSource, type SourceText } from './text.js'
export { ocrImage, ocrPages, prewarmOcr } from './ocr.js'
export { chatJson } from './llm.js'
export { splitSections, sectionIndex } from './sections.js'
export { sha256 } from './cache.js'
export { env, hasModelProvider } from './env.js'
