/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ExceptionsRouteImport } from './routes/exceptions'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ScorecardRouteImport } from './routes/scorecard'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminChecklistRouteImport } from './routes/admin.checklist'
import { Route as AdminDocumentTypesRouteImport } from './routes/admin.document-types'
import { Route as AdminPolicyRouteImport } from './routes/admin.policy'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AppraisalsIndexRouteImport } from './routes/appraisals.index'
import { Route as AppraisalsCaseIdRouteImport } from './routes/appraisals.$caseId'
import { Route as AppraisalsNewRouteImport } from './routes/appraisals.new'
import { Route as DocreadyIndexRouteImport } from './routes/docready.index'
import { Route as DocreadySplatRouteImport } from './routes/docready.$'
import { Route as AppraisalsCaseIdIndexRouteImport } from './routes/appraisals.$caseId.index'
import { Route as AppraisalsCaseIdStepRouteImport } from './routes/appraisals.$caseId.$step'
import { Route as AppraisalsCaseIdComparisonRouteImport } from './routes/appraisals.$caseId.comparison'
import { Route as AppraisalsCaseIdCompletenessRouteImport } from './routes/appraisals.$caseId.completeness'
import { Route as AppraisalsCaseIdCrossVerificationRouteImport } from './routes/appraisals.$caseId.cross-verification'
import { Route as AppraisalsCaseIdDocumentsRouteImport } from './routes/appraisals.$caseId.documents'
import { Route as AppraisalsCaseIdExtractionRouteImport } from './routes/appraisals.$caseId.extraction'
import { Route as AppraisalsCaseIdOutputsRouteImport } from './routes/appraisals.$caseId.outputs'
import { Route as AppraisalsCaseIdPolicyRouteImport } from './routes/appraisals.$caseId.policy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ExceptionsRoute = ExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ScorecardRoute = ScorecardRouteImport.update({
  id: '/scorecard',
  path: '/scorecard',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChecklistRoute = AdminChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentTypesRoute = AdminDocumentTypesRouteImport.update({
  id: '/document-types',
  path: '/document-types',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPolicyRoute = AdminPolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AppraisalsIndexRoute = AppraisalsIndexRouteImport.update({
  id: '/appraisals/',
  path: '/appraisals/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppraisalsCaseIdRoute = AppraisalsCaseIdRouteImport.update({
  id: '/appraisals/$caseId',
  path: '/appraisals/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppraisalsNewRoute = AppraisalsNewRouteImport.update({
  id: '/appraisals/new',
  path: '/appraisals/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DocreadyIndexRoute = DocreadyIndexRouteImport.update({
  id: '/docready/',
  path: '/docready/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocreadySplatRoute = DocreadySplatRouteImport.update({
  id: '/docready/$',
  path: '/docready/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppraisalsCaseIdIndexRoute = AppraisalsCaseIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppraisalsCaseIdRoute,
} as any)
const AppraisalsCaseIdStepRoute = AppraisalsCaseIdStepRouteImport.update({
  id: '/$step',
  path: '/$step',
  getParentRoute: () => AppraisalsCaseIdRoute,
} as any)
const AppraisalsCaseIdComparisonRoute =
  AppraisalsCaseIdComparisonRouteImport.update({
    id: '/comparison',
    path: '/comparison',
    getParentRoute: () => AppraisalsCaseIdRoute,
  } as any)
const AppraisalsCaseIdCompletenessRoute =
  AppraisalsCaseIdCompletenessRouteImport.update({
    id: '/completeness',
    path: '/completeness',
    getParentRoute: () => AppraisalsCaseIdRoute,
  } as any)
const AppraisalsCaseIdCrossVerificationRoute =
  AppraisalsCaseIdCrossVerificationRouteImport.update({
    id: '/cross-verification',
    path: '/cross-verification',
    getParentRoute: () => AppraisalsCaseIdRoute,
  } as any)
const AppraisalsCaseIdDocumentsRoute =
  AppraisalsCaseIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AppraisalsCaseIdRoute,
  } as any)
const AppraisalsCaseIdExtractionRoute =
  AppraisalsCaseIdExtractionRouteImport.update({
    id: '/extraction',
    path: '/extraction',
    getParentRoute: () => AppraisalsCaseIdRoute,
  } as any)
const AppraisalsCaseIdOutputsRoute = AppraisalsCaseIdOutputsRouteImport.update({
  id: '/outputs',
  path: '/outputs',
  getParentRoute: () => AppraisalsCaseIdRoute,
} as any)
const AppraisalsCaseIdPolicyRoute = AppraisalsCaseIdPolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => AppraisalsCaseIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/audit': typeof AuditRoute
  '/exceptions': typeof ExceptionsRoute
  '/help': typeof HelpRoute
  '/review': typeof ReviewRoute
  '/scorecard': typeof ScorecardRoute
  '/sign-in': typeof SignInRoute
  '/admin/checklist': typeof AdminChecklistRoute
  '/admin/document-types': typeof AdminDocumentTypesRoute
  '/admin/policy': typeof AdminPolicyRoute
  '/admin/users': typeof AdminUsersRoute
  '/appraisals/$caseId': typeof AppraisalsCaseIdRouteWithChildren
  '/appraisals/new': typeof AppraisalsNewRoute
  '/docready/$': typeof DocreadySplatRoute
  '/admin/': typeof AdminIndexRoute
  '/appraisals/': typeof AppraisalsIndexRoute
  '/docready/': typeof DocreadyIndexRoute
  '/appraisals/$caseId/$step': typeof AppraisalsCaseIdStepRoute
  '/appraisals/$caseId/comparison': typeof AppraisalsCaseIdComparisonRoute
  '/appraisals/$caseId/completeness': typeof AppraisalsCaseIdCompletenessRoute
  '/appraisals/$caseId/cross-verification': typeof AppraisalsCaseIdCrossVerificationRoute
  '/appraisals/$caseId/documents': typeof AppraisalsCaseIdDocumentsRoute
  '/appraisals/$caseId/extraction': typeof AppraisalsCaseIdExtractionRoute
  '/appraisals/$caseId/outputs': typeof AppraisalsCaseIdOutputsRoute
  '/appraisals/$caseId/policy': typeof AppraisalsCaseIdPolicyRoute
  '/appraisals/$caseId/': typeof AppraisalsCaseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/exceptions': typeof ExceptionsRoute
  '/help': typeof HelpRoute
  '/review': typeof ReviewRoute
  '/scorecard': typeof ScorecardRoute
  '/sign-in': typeof SignInRoute
  '/admin/checklist': typeof AdminChecklistRoute
  '/admin/document-types': typeof AdminDocumentTypesRoute
  '/admin/policy': typeof AdminPolicyRoute
  '/admin/users': typeof AdminUsersRoute
  '/appraisals/new': typeof AppraisalsNewRoute
  '/docready/$': typeof DocreadySplatRoute
  '/admin': typeof AdminIndexRoute
  '/appraisals': typeof AppraisalsIndexRoute
  '/docready': typeof DocreadyIndexRoute
  '/appraisals/$caseId/$step': typeof AppraisalsCaseIdStepRoute
  '/appraisals/$caseId/comparison': typeof AppraisalsCaseIdComparisonRoute
  '/appraisals/$caseId/completeness': typeof AppraisalsCaseIdCompletenessRoute
  '/appraisals/$caseId/cross-verification': typeof AppraisalsCaseIdCrossVerificationRoute
  '/appraisals/$caseId/documents': typeof AppraisalsCaseIdDocumentsRoute
  '/appraisals/$caseId/extraction': typeof AppraisalsCaseIdExtractionRoute
  '/appraisals/$caseId/outputs': typeof AppraisalsCaseIdOutputsRoute
  '/appraisals/$caseId/policy': typeof AppraisalsCaseIdPolicyRoute
  '/appraisals/$caseId': typeof AppraisalsCaseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/audit': typeof AuditRoute
  '/exceptions': typeof ExceptionsRoute
  '/help': typeof HelpRoute
  '/review': typeof ReviewRoute
  '/scorecard': typeof ScorecardRoute
  '/sign-in': typeof SignInRoute
  '/admin/checklist': typeof AdminChecklistRoute
  '/admin/document-types': typeof AdminDocumentTypesRoute
  '/admin/policy': typeof AdminPolicyRoute
  '/admin/users': typeof AdminUsersRoute
  '/appraisals/$caseId': typeof AppraisalsCaseIdRouteWithChildren
  '/appraisals/new': typeof AppraisalsNewRoute
  '/docready/$': typeof DocreadySplatRoute
  '/admin/': typeof AdminIndexRoute
  '/appraisals/': typeof AppraisalsIndexRoute
  '/docready/': typeof DocreadyIndexRoute
  '/appraisals/$caseId/$step': typeof AppraisalsCaseIdStepRoute
  '/appraisals/$caseId/comparison': typeof AppraisalsCaseIdComparisonRoute
  '/appraisals/$caseId/completeness': typeof AppraisalsCaseIdCompletenessRoute
  '/appraisals/$caseId/cross-verification': typeof AppraisalsCaseIdCrossVerificationRoute
  '/appraisals/$caseId/documents': typeof AppraisalsCaseIdDocumentsRoute
  '/appraisals/$caseId/extraction': typeof AppraisalsCaseIdExtractionRoute
  '/appraisals/$caseId/outputs': typeof AppraisalsCaseIdOutputsRoute
  '/appraisals/$caseId/policy': typeof AppraisalsCaseIdPolicyRoute
  '/appraisals/$caseId/': typeof AppraisalsCaseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/audit'
    | '/exceptions'
    | '/help'
    | '/review'
    | '/scorecard'
    | '/sign-in'
    | '/admin/checklist'
    | '/admin/document-types'
    | '/admin/policy'
    | '/admin/users'
    | '/appraisals/$caseId'
    | '/appraisals/new'
    | '/docready/$'
    | '/admin/'
    | '/appraisals/'
    | '/docready/'
    | '/appraisals/$caseId/$step'
    | '/appraisals/$caseId/comparison'
    | '/appraisals/$caseId/completeness'
    | '/appraisals/$caseId/cross-verification'
    | '/appraisals/$caseId/documents'
    | '/appraisals/$caseId/extraction'
    | '/appraisals/$caseId/outputs'
    | '/appraisals/$caseId/policy'
    | '/appraisals/$caseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/exceptions'
    | '/help'
    | '/review'
    | '/scorecard'
    | '/sign-in'
    | '/admin/checklist'
    | '/admin/document-types'
    | '/admin/policy'
    | '/admin/users'
    | '/appraisals/new'
    | '/docready/$'
    | '/admin'
    | '/appraisals'
    | '/docready'
    | '/appraisals/$caseId/$step'
    | '/appraisals/$caseId/comparison'
    | '/appraisals/$caseId/completeness'
    | '/appraisals/$caseId/cross-verification'
    | '/appraisals/$caseId/documents'
    | '/appraisals/$caseId/extraction'
    | '/appraisals/$caseId/outputs'
    | '/appraisals/$caseId/policy'
    | '/appraisals/$caseId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/audit'
    | '/exceptions'
    | '/help'
    | '/review'
    | '/scorecard'
    | '/sign-in'
    | '/admin/checklist'
    | '/admin/document-types'
    | '/admin/policy'
    | '/admin/users'
    | '/appraisals/$caseId'
    | '/appraisals/new'
    | '/docready/$'
    | '/admin/'
    | '/appraisals/'
    | '/docready/'
    | '/appraisals/$caseId/$step'
    | '/appraisals/$caseId/comparison'
    | '/appraisals/$caseId/completeness'
    | '/appraisals/$caseId/cross-verification'
    | '/appraisals/$caseId/documents'
    | '/appraisals/$caseId/extraction'
    | '/appraisals/$caseId/outputs'
    | '/appraisals/$caseId/policy'
    | '/appraisals/$caseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuditRoute: typeof AuditRoute
  ExceptionsRoute: typeof ExceptionsRoute
  HelpRoute: typeof HelpRoute
  ReviewRoute: typeof ReviewRoute
  ScorecardRoute: typeof ScorecardRoute
  SignInRoute: typeof SignInRoute
  AppraisalsCaseIdRoute: typeof AppraisalsCaseIdRouteWithChildren
  AppraisalsNewRoute: typeof AppraisalsNewRoute
  DocreadySplatRoute: typeof DocreadySplatRoute
  AppraisalsIndexRoute: typeof AppraisalsIndexRoute
  DocreadyIndexRoute: typeof DocreadyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exceptions': {
      id: '/exceptions'
      path: '/exceptions'
      fullPath: '/exceptions'
      preLoaderRoute: typeof ExceptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scorecard': {
      id: '/scorecard'
      path: '/scorecard'
      fullPath: '/scorecard'
      preLoaderRoute: typeof ScorecardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/checklist': {
      id: '/admin/checklist'
      path: '/checklist'
      fullPath: '/admin/checklist'
      preLoaderRoute: typeof AdminChecklistRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/document-types': {
      id: '/admin/document-types'
      path: '/document-types'
      fullPath: '/admin/document-types'
      preLoaderRoute: typeof AdminDocumentTypesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/policy': {
      id: '/admin/policy'
      path: '/policy'
      fullPath: '/admin/policy'
      preLoaderRoute: typeof AdminPolicyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/appraisals/': {
      id: '/appraisals/'
      path: '/appraisals'
      fullPath: '/appraisals/'
      preLoaderRoute: typeof AppraisalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appraisals/$caseId': {
      id: '/appraisals/$caseId'
      path: '/appraisals/$caseId'
      fullPath: '/appraisals/$caseId'
      preLoaderRoute: typeof AppraisalsCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appraisals/new': {
      id: '/appraisals/new'
      path: '/appraisals/new'
      fullPath: '/appraisals/new'
      preLoaderRoute: typeof AppraisalsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docready/': {
      id: '/docready/'
      path: '/docready'
      fullPath: '/docready/'
      preLoaderRoute: typeof DocreadyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docready/$': {
      id: '/docready/$'
      path: '/docready/$'
      fullPath: '/docready/$'
      preLoaderRoute: typeof DocreadySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appraisals/$caseId/': {
      id: '/appraisals/$caseId/'
      path: '/'
      fullPath: '/appraisals/$caseId/'
      preLoaderRoute: typeof AppraisalsCaseIdIndexRouteImport
      parentRoute: typeof AppraisalsCaseIdRoute
    }
    '/appraisals/$caseId/$step': {
      id: '/appraisals/$caseId/$step'
      path: '/$step'
      fullPath: '/appraisals/$caseId/$step'
      preLoaderRoute: typeof AppraisalsCaseIdStepRouteImport
      parentRoute: typeof AppraisalsCaseIdRoute
    }
    '/appraisals/$caseId/comparison': {
      id: '/appraisals/$caseId/comparison'
      path: '/comparison'
      fullPath: '/appraisals/$caseId/comparison'
      preLoaderRoute: typeof AppraisalsCaseIdComparisonRouteImport
      parentRoute: typeof AppraisalsCaseIdRoute
    }
    '/appraisals/$caseId/completeness': {
      id: '/appraisals/$caseId/completeness'
      path: '/completeness'
      fullPath: '/appraisals/$caseId/completeness'
      preLoaderRoute: typeof AppraisalsCaseIdCompletenessRouteImport
      parentRoute: typeof AppraisalsCaseIdRoute
    }
    '/appraisals/$caseId/cross-verification': {
      id: '/appraisals/$caseId/cross-verification'
      path: '/cross-verification'
      fullPath: '/appraisals/$caseId/cross-verification'
      preLoaderRoute: typeof AppraisalsCaseIdCrossVerificationRouteImport
      parentRoute: typeof AppraisalsCaseIdRoute
    }
    '/appraisals/$caseId/documents': {
      id: '/appraisals/$caseId/documents'
      path: '/documents'
      fullPath: '/appraisals/$caseId/documents'
      preLoaderRoute: typeof AppraisalsCaseIdDocumentsRouteImport
      parentRoute: typeof AppraisalsCaseIdRoute
    }
    '/appraisals/$caseId/extraction': {
      id: '/appraisals/$caseId/extraction'
      path: '/extraction'
      fullPath: '/appraisals/$caseId/extraction'
      preLoaderRoute: typeof AppraisalsCaseIdExtractionRouteImport
      parentRoute: typeof AppraisalsCaseIdRoute
    }
    '/appraisals/$caseId/outputs': {
      id: '/appraisals/$caseId/outputs'
      path: '/outputs'
      fullPath: '/appraisals/$caseId/outputs'
      preLoaderRoute: typeof AppraisalsCaseIdOutputsRouteImport
      parentRoute: typeof AppraisalsCaseIdRoute
    }
    '/appraisals/$caseId/policy': {
      id: '/appraisals/$caseId/policy'
      path: '/policy'
      fullPath: '/appraisals/$caseId/policy'
      preLoaderRoute: typeof AppraisalsCaseIdPolicyRouteImport
      parentRoute: typeof AppraisalsCaseIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminChecklistRoute: typeof AdminChecklistRoute
  AdminDocumentTypesRoute: typeof AdminDocumentTypesRoute
  AdminPolicyRoute: typeof AdminPolicyRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminChecklistRoute: AdminChecklistRoute,
  AdminDocumentTypesRoute: AdminDocumentTypesRoute,
  AdminPolicyRoute: AdminPolicyRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppraisalsCaseIdRouteChildren {
  AppraisalsCaseIdStepRoute: typeof AppraisalsCaseIdStepRoute
  AppraisalsCaseIdComparisonRoute: typeof AppraisalsCaseIdComparisonRoute
  AppraisalsCaseIdCompletenessRoute: typeof AppraisalsCaseIdCompletenessRoute
  AppraisalsCaseIdCrossVerificationRoute: typeof AppraisalsCaseIdCrossVerificationRoute
  AppraisalsCaseIdDocumentsRoute: typeof AppraisalsCaseIdDocumentsRoute
  AppraisalsCaseIdExtractionRoute: typeof AppraisalsCaseIdExtractionRoute
  AppraisalsCaseIdOutputsRoute: typeof AppraisalsCaseIdOutputsRoute
  AppraisalsCaseIdPolicyRoute: typeof AppraisalsCaseIdPolicyRoute
  AppraisalsCaseIdIndexRoute: typeof AppraisalsCaseIdIndexRoute
}

const AppraisalsCaseIdRouteChildren: AppraisalsCaseIdRouteChildren = {
  AppraisalsCaseIdStepRoute: AppraisalsCaseIdStepRoute,
  AppraisalsCaseIdComparisonRoute: AppraisalsCaseIdComparisonRoute,
  AppraisalsCaseIdCompletenessRoute: AppraisalsCaseIdCompletenessRoute,
  AppraisalsCaseIdCrossVerificationRoute:
    AppraisalsCaseIdCrossVerificationRoute,
  AppraisalsCaseIdDocumentsRoute: AppraisalsCaseIdDocumentsRoute,
  AppraisalsCaseIdExtractionRoute: AppraisalsCaseIdExtractionRoute,
  AppraisalsCaseIdOutputsRoute: AppraisalsCaseIdOutputsRoute,
  AppraisalsCaseIdPolicyRoute: AppraisalsCaseIdPolicyRoute,
  AppraisalsCaseIdIndexRoute: AppraisalsCaseIdIndexRoute,
}

const AppraisalsCaseIdRouteWithChildren =
  AppraisalsCaseIdRoute._addFileChildren(AppraisalsCaseIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuditRoute: AuditRoute,
  ExceptionsRoute: ExceptionsRoute,
  HelpRoute: HelpRoute,
  ReviewRoute: ReviewRoute,
  ScorecardRoute: ScorecardRoute,
  SignInRoute: SignInRoute,
  AppraisalsCaseIdRoute: AppraisalsCaseIdRouteWithChildren,
  AppraisalsNewRoute: AppraisalsNewRoute,
  DocreadySplatRoute: DocreadySplatRoute,
  AppraisalsIndexRoute: AppraisalsIndexRoute,
  DocreadyIndexRoute: DocreadyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
