/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExceptionsRouteImport } from './routes/exceptions'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ScorecardRouteImport } from './routes/scorecard'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppraisalsIndexRouteImport } from './routes/appraisals.index'
import { Route as AppraisalsSplatRouteImport } from './routes/appraisals.$'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'
import { Route as CasesNewRouteImport } from './routes/cases.new'
import { Route as DocreadyIndexRouteImport } from './routes/docready.index'
import { Route as DocreadySplatRouteImport } from './routes/docready.$'
import { Route as CasesCaseIdIndexRouteImport } from './routes/cases.$caseId.index'
import { Route as CasesCaseIdComparisonRouteImport } from './routes/cases.$caseId.comparison'
import { Route as CasesCaseIdCompletenessRouteImport } from './routes/cases.$caseId.completeness'
import { Route as CasesCaseIdCrossVerificationRouteImport } from './routes/cases.$caseId.cross-verification'
import { Route as CasesCaseIdDocumentsRouteImport } from './routes/cases.$caseId.documents'
import { Route as CasesCaseIdExtractionRouteImport } from './routes/cases.$caseId.extraction'
import { Route as CasesCaseIdOutputsRouteImport } from './routes/cases.$caseId.outputs'
import { Route as CasesCaseIdPolicyRouteImport } from './routes/cases.$caseId.policy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExceptionsRoute = ExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ScorecardRoute = ScorecardRouteImport.update({
  id: '/scorecard',
  path: '/scorecard',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppraisalsIndexRoute = AppraisalsIndexRouteImport.update({
  id: '/appraisals/',
  path: '/appraisals/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppraisalsSplatRoute = AppraisalsSplatRouteImport.update({
  id: '/appraisals/$',
  path: '/appraisals/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesNewRoute = CasesNewRouteImport.update({
  id: '/cases/new',
  path: '/cases/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DocreadyIndexRoute = DocreadyIndexRouteImport.update({
  id: '/docready/',
  path: '/docready/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocreadySplatRoute = DocreadySplatRouteImport.update({
  id: '/docready/$',
  path: '/docready/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdIndexRoute = CasesCaseIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CasesCaseIdRoute,
} as any)
const CasesCaseIdComparisonRoute = CasesCaseIdComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => CasesCaseIdRoute,
} as any)
const CasesCaseIdCompletenessRoute = CasesCaseIdCompletenessRouteImport.update({
  id: '/completeness',
  path: '/completeness',
  getParentRoute: () => CasesCaseIdRoute,
} as any)
const CasesCaseIdCrossVerificationRoute =
  CasesCaseIdCrossVerificationRouteImport.update({
    id: '/cross-verification',
    path: '/cross-verification',
    getParentRoute: () => CasesCaseIdRoute,
  } as any)
const CasesCaseIdDocumentsRoute = CasesCaseIdDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => CasesCaseIdRoute,
} as any)
const CasesCaseIdExtractionRoute = CasesCaseIdExtractionRouteImport.update({
  id: '/extraction',
  path: '/extraction',
  getParentRoute: () => CasesCaseIdRoute,
} as any)
const CasesCaseIdOutputsRoute = CasesCaseIdOutputsRouteImport.update({
  id: '/outputs',
  path: '/outputs',
  getParentRoute: () => CasesCaseIdRoute,
} as any)
const CasesCaseIdPolicyRoute = CasesCaseIdPolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => CasesCaseIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exceptions': typeof ExceptionsRoute
  '/review': typeof ReviewRoute
  '/scorecard': typeof ScorecardRoute
  '/sign-in': typeof SignInRoute
  '/appraisals/$': typeof AppraisalsSplatRoute
  '/cases/$caseId': typeof CasesCaseIdRouteWithChildren
  '/cases/new': typeof CasesNewRoute
  '/docready/$': typeof DocreadySplatRoute
  '/appraisals/': typeof AppraisalsIndexRoute
  '/docready/': typeof DocreadyIndexRoute
  '/cases/$caseId/comparison': typeof CasesCaseIdComparisonRoute
  '/cases/$caseId/completeness': typeof CasesCaseIdCompletenessRoute
  '/cases/$caseId/cross-verification': typeof CasesCaseIdCrossVerificationRoute
  '/cases/$caseId/documents': typeof CasesCaseIdDocumentsRoute
  '/cases/$caseId/extraction': typeof CasesCaseIdExtractionRoute
  '/cases/$caseId/outputs': typeof CasesCaseIdOutputsRoute
  '/cases/$caseId/policy': typeof CasesCaseIdPolicyRoute
  '/cases/$caseId/': typeof CasesCaseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exceptions': typeof ExceptionsRoute
  '/review': typeof ReviewRoute
  '/scorecard': typeof ScorecardRoute
  '/sign-in': typeof SignInRoute
  '/appraisals/$': typeof AppraisalsSplatRoute
  '/cases/new': typeof CasesNewRoute
  '/docready/$': typeof DocreadySplatRoute
  '/appraisals': typeof AppraisalsIndexRoute
  '/docready': typeof DocreadyIndexRoute
  '/cases/$caseId/comparison': typeof CasesCaseIdComparisonRoute
  '/cases/$caseId/completeness': typeof CasesCaseIdCompletenessRoute
  '/cases/$caseId/cross-verification': typeof CasesCaseIdCrossVerificationRoute
  '/cases/$caseId/documents': typeof CasesCaseIdDocumentsRoute
  '/cases/$caseId/extraction': typeof CasesCaseIdExtractionRoute
  '/cases/$caseId/outputs': typeof CasesCaseIdOutputsRoute
  '/cases/$caseId/policy': typeof CasesCaseIdPolicyRoute
  '/cases/$caseId': typeof CasesCaseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exceptions': typeof ExceptionsRoute
  '/review': typeof ReviewRoute
  '/scorecard': typeof ScorecardRoute
  '/sign-in': typeof SignInRoute
  '/appraisals/$': typeof AppraisalsSplatRoute
  '/cases/$caseId': typeof CasesCaseIdRouteWithChildren
  '/cases/new': typeof CasesNewRoute
  '/docready/$': typeof DocreadySplatRoute
  '/appraisals/': typeof AppraisalsIndexRoute
  '/docready/': typeof DocreadyIndexRoute
  '/cases/$caseId/comparison': typeof CasesCaseIdComparisonRoute
  '/cases/$caseId/completeness': typeof CasesCaseIdCompletenessRoute
  '/cases/$caseId/cross-verification': typeof CasesCaseIdCrossVerificationRoute
  '/cases/$caseId/documents': typeof CasesCaseIdDocumentsRoute
  '/cases/$caseId/extraction': typeof CasesCaseIdExtractionRoute
  '/cases/$caseId/outputs': typeof CasesCaseIdOutputsRoute
  '/cases/$caseId/policy': typeof CasesCaseIdPolicyRoute
  '/cases/$caseId/': typeof CasesCaseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exceptions'
    | '/review'
    | '/scorecard'
    | '/sign-in'
    | '/appraisals/$'
    | '/cases/$caseId'
    | '/cases/new'
    | '/docready/$'
    | '/appraisals/'
    | '/docready/'
    | '/cases/$caseId/comparison'
    | '/cases/$caseId/completeness'
    | '/cases/$caseId/cross-verification'
    | '/cases/$caseId/documents'
    | '/cases/$caseId/extraction'
    | '/cases/$caseId/outputs'
    | '/cases/$caseId/policy'
    | '/cases/$caseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exceptions'
    | '/review'
    | '/scorecard'
    | '/sign-in'
    | '/appraisals/$'
    | '/cases/new'
    | '/docready/$'
    | '/appraisals'
    | '/docready'
    | '/cases/$caseId/comparison'
    | '/cases/$caseId/completeness'
    | '/cases/$caseId/cross-verification'
    | '/cases/$caseId/documents'
    | '/cases/$caseId/extraction'
    | '/cases/$caseId/outputs'
    | '/cases/$caseId/policy'
    | '/cases/$caseId'
  id:
    | '__root__'
    | '/'
    | '/exceptions'
    | '/review'
    | '/scorecard'
    | '/sign-in'
    | '/appraisals/$'
    | '/cases/$caseId'
    | '/cases/new'
    | '/docready/$'
    | '/appraisals/'
    | '/docready/'
    | '/cases/$caseId/comparison'
    | '/cases/$caseId/completeness'
    | '/cases/$caseId/cross-verification'
    | '/cases/$caseId/documents'
    | '/cases/$caseId/extraction'
    | '/cases/$caseId/outputs'
    | '/cases/$caseId/policy'
    | '/cases/$caseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExceptionsRoute: typeof ExceptionsRoute
  ReviewRoute: typeof ReviewRoute
  ScorecardRoute: typeof ScorecardRoute
  SignInRoute: typeof SignInRoute
  AppraisalsSplatRoute: typeof AppraisalsSplatRoute
  CasesCaseIdRoute: typeof CasesCaseIdRouteWithChildren
  CasesNewRoute: typeof CasesNewRoute
  DocreadySplatRoute: typeof DocreadySplatRoute
  AppraisalsIndexRoute: typeof AppraisalsIndexRoute
  DocreadyIndexRoute: typeof DocreadyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exceptions': {
      id: '/exceptions'
      path: '/exceptions'
      fullPath: '/exceptions'
      preLoaderRoute: typeof ExceptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scorecard': {
      id: '/scorecard'
      path: '/scorecard'
      fullPath: '/scorecard'
      preLoaderRoute: typeof ScorecardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appraisals/': {
      id: '/appraisals/'
      path: '/appraisals'
      fullPath: '/appraisals/'
      preLoaderRoute: typeof AppraisalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appraisals/$': {
      id: '/appraisals/$'
      path: '/appraisals/$'
      fullPath: '/appraisals/$'
      preLoaderRoute: typeof AppraisalsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/new': {
      id: '/cases/new'
      path: '/cases/new'
      fullPath: '/cases/new'
      preLoaderRoute: typeof CasesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docready/': {
      id: '/docready/'
      path: '/docready'
      fullPath: '/docready/'
      preLoaderRoute: typeof DocreadyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docready/$': {
      id: '/docready/$'
      path: '/docready/$'
      fullPath: '/docready/$'
      preLoaderRoute: typeof DocreadySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId/': {
      id: '/cases/$caseId/'
      path: '/'
      fullPath: '/cases/$caseId/'
      preLoaderRoute: typeof CasesCaseIdIndexRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
    '/cases/$caseId/comparison': {
      id: '/cases/$caseId/comparison'
      path: '/comparison'
      fullPath: '/cases/$caseId/comparison'
      preLoaderRoute: typeof CasesCaseIdComparisonRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
    '/cases/$caseId/completeness': {
      id: '/cases/$caseId/completeness'
      path: '/completeness'
      fullPath: '/cases/$caseId/completeness'
      preLoaderRoute: typeof CasesCaseIdCompletenessRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
    '/cases/$caseId/cross-verification': {
      id: '/cases/$caseId/cross-verification'
      path: '/cross-verification'
      fullPath: '/cases/$caseId/cross-verification'
      preLoaderRoute: typeof CasesCaseIdCrossVerificationRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
    '/cases/$caseId/documents': {
      id: '/cases/$caseId/documents'
      path: '/documents'
      fullPath: '/cases/$caseId/documents'
      preLoaderRoute: typeof CasesCaseIdDocumentsRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
    '/cases/$caseId/extraction': {
      id: '/cases/$caseId/extraction'
      path: '/extraction'
      fullPath: '/cases/$caseId/extraction'
      preLoaderRoute: typeof CasesCaseIdExtractionRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
    '/cases/$caseId/outputs': {
      id: '/cases/$caseId/outputs'
      path: '/outputs'
      fullPath: '/cases/$caseId/outputs'
      preLoaderRoute: typeof CasesCaseIdOutputsRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
    '/cases/$caseId/policy': {
      id: '/cases/$caseId/policy'
      path: '/policy'
      fullPath: '/cases/$caseId/policy'
      preLoaderRoute: typeof CasesCaseIdPolicyRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
  }
}

interface CasesCaseIdRouteChildren {
  CasesCaseIdComparisonRoute: typeof CasesCaseIdComparisonRoute
  CasesCaseIdCompletenessRoute: typeof CasesCaseIdCompletenessRoute
  CasesCaseIdCrossVerificationRoute: typeof CasesCaseIdCrossVerificationRoute
  CasesCaseIdDocumentsRoute: typeof CasesCaseIdDocumentsRoute
  CasesCaseIdExtractionRoute: typeof CasesCaseIdExtractionRoute
  CasesCaseIdOutputsRoute: typeof CasesCaseIdOutputsRoute
  CasesCaseIdPolicyRoute: typeof CasesCaseIdPolicyRoute
  CasesCaseIdIndexRoute: typeof CasesCaseIdIndexRoute
}

const CasesCaseIdRouteChildren: CasesCaseIdRouteChildren = {
  CasesCaseIdComparisonRoute: CasesCaseIdComparisonRoute,
  CasesCaseIdCompletenessRoute: CasesCaseIdCompletenessRoute,
  CasesCaseIdCrossVerificationRoute: CasesCaseIdCrossVerificationRoute,
  CasesCaseIdDocumentsRoute: CasesCaseIdDocumentsRoute,
  CasesCaseIdExtractionRoute: CasesCaseIdExtractionRoute,
  CasesCaseIdOutputsRoute: CasesCaseIdOutputsRoute,
  CasesCaseIdPolicyRoute: CasesCaseIdPolicyRoute,
  CasesCaseIdIndexRoute: CasesCaseIdIndexRoute,
}

const CasesCaseIdRouteWithChildren = CasesCaseIdRoute._addFileChildren(
  CasesCaseIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExceptionsRoute: ExceptionsRoute,
  ReviewRoute: ReviewRoute,
  ScorecardRoute: ScorecardRoute,
  SignInRoute: SignInRoute,
  AppraisalsSplatRoute: AppraisalsSplatRoute,
  CasesCaseIdRoute: CasesCaseIdRouteWithChildren,
  CasesNewRoute: CasesNewRoute,
  DocreadySplatRoute: DocreadySplatRoute,
  AppraisalsIndexRoute: AppraisalsIndexRoute,
  DocreadyIndexRoute: DocreadyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
